import {inject, TestBed, waitForAsync} from '@angular/core/testing';
import {DtsService} from './dts.service';
import {HttpClient, HttpHandler} from '@angular/common/http';
import {of, throwError} from 'rxjs';
import {templatesAll, templatesEnrollment} from '../../test/templates';
import {template} from '../../test/template';
import {documentData} from 'src/test/document-data';

describe('DtsService', () => {
  let service: DtsService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        HttpClient,
        HttpHandler
      ]
    });
    service = TestBed.inject(DtsService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('should return an OK status when checking service health', waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
      const serviceSpy = spyOn(http, 'get').and.returnValue(of('OK'));

      dtsService.getStatus().subscribe(result => {
        expect(result).toEqual('OK');
        expect(serviceSpy).toHaveBeenCalled();
      });
    })));

  it('should return a list of all templates', waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
      const serviceSpy = spyOn(http, 'get').and.returnValue(of(templatesAll));

      dtsService.getTemplates().subscribe(result => {
        expect(result[0].id).toBe('2fa85f64-5717-4562-b3fc-2c963f66afa6');
        expect(result[1].id).toBe('3fa85f64-5717-4562-b3fc-2c963f66afa6');
        expect(result[2].id).toBe('1fa85f64-5717-4562-b3fc-2c963f66afa6');
        expect(serviceSpy).toHaveBeenCalled();
      });
    })));

  it('should return a templates by document type', waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
      const serviceSpy = spyOn(http, 'get').and.returnValue(of(templatesEnrollment));

      dtsService.getTemplates('enrollment').subscribe(result => {
        expect(result[0].id).toBe('3fa85f64-5717-4562-b3fc-2c963f66afa6');
        expect(result[1].id).toBe('1fa85f64-5717-4562-b3fc-2c963f66afa6');
        expect(serviceSpy).toHaveBeenCalled();
      });
    })));

  it('should return a template given a document type and template key', waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
      const serviceSpy = spyOn(http, 'get').and.returnValue(of(template));

      dtsService.getTemplateByKey('', '').subscribe(result => {
        expect(result).toEqual(template);
        expect(serviceSpy).toHaveBeenCalled();
      });
    })));

  it('should retrieve document data given a document id', waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
      const serviceSpy = spyOn(http, 'get').and.returnValue(of(documentData));

      dtsService.getDocumentData('').subscribe((result: any) => {
        expect(result).toEqual(documentData.data);
        expect(serviceSpy).toHaveBeenCalled();
      });
    })));

  it('should retrieve a hot render response given template content and data', waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
    const hotRenderResponse = {
      id: '34b3a03c-9e28-11eb-b49c-0242ac110003',
      createdAt: {
        date: '2021-04-15 20:21:48.500043',
        timezone_type: 3,
        timezone: 'UTC'
      },
      location: '/api/v1/hotrender/34b3a03c-9e28-11eb-b49c-0242ac110003'
    };
    const serviceSpy = spyOn(http, 'post').and.returnValue(of(hotRenderResponse));

    dtsService.hotRenderTemplate('', '').subscribe((result: any) => {
      expect(result).toEqual(hotRenderResponse);
      expect(serviceSpy).toHaveBeenCalled();
    });
  })));

  it('should throw an error searching for a template given a document type and template key which does not exist',
    waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
      const serviceSpy = spyOn(http, 'get').and.returnValue(throwError({
        error: {
          code: '404',
        }
      }));

      dtsService.getTemplateByKey('', '').subscribe(result => {
        expect(result).toEqual(null);
        expect(serviceSpy).toHaveBeenCalled();
      });
    })));

  it('should save a template given a document type, template key, and author', waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
      const url =  `${dtsService.url}/template`;

      const postData = {
        docType: 'enrollment',
        key: 'default-ce',
        author: 'Robert Martin',
        body: template
      };

      const postResponse = {
        id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',       /* generated by the backend */
        docType: postData.docType,
        key: postData.key,
        author: postData.author,
        createdAt: {
          date: '2020-03-23 15:40:06.000000',
          timezone_type: 3,
          timezone: 'UTC'
        },
        bodyUri: '/template/3fa85f64-5717-4562-b3fc-2c963f66afa6' /* generated by the backend */
      };

      const serviceSpy = spyOn(http, 'post')
        .withArgs(url, postData)
        .and.returnValue(of(postResponse));

      dtsService.saveTemplate(postData.key, postData.author, template).subscribe(result => {
        expect(result).toEqual(postResponse);
        expect(serviceSpy).toHaveBeenCalled();
      });
    })));

  it('should handle an error when saving a template given a document type, template key, and author',
    waitForAsync(inject([DtsService, HttpClient],
    (dtsService: DtsService, http: HttpClient) => {
      const url =  `${dtsService.url}/template`;

      const postData = {
        docType: 'enrollment',
        key: 'default-ce',
        author: 'Robert Martin',
        body: template
      };

      spyOn(http, 'post')
        .withArgs(url, postData)
        .and.returnValue(throwError({
          error: {
            code: 400,
          }
        }));

      let saveError = null;
      dtsService.saveTemplate(postData.key, postData.author, template).subscribe(
        () => { },
        err => {
          saveError = err;
        });

      expect(saveError.error.code).toEqual(400);
    })));
});
